my_string = input("Расскажи анекдот) (без знаков припинания :'э) ")
print('Колличество символов в ответе -', len(my_string))
print('Колличество букв в ответе -', len(my_string.replace(' ', '')))
print('Колличество пробелов в ответе -', len(my_string) - len(my_string.replace(' ', '')))
print('Верхний регистр -', my_string.upper())
print('Нижний регистр -', my_string.lower())
print("Без пробелов -", my_string.replace(" ", ""))
print("Первый символ -", my_string[0])
print("Последний символ -", my_string[-1])
